name: form-manager
recipe: laravel
config:
  webroot: public
  php: '7.4'
  composer_version: 2-latest
  xdebug: true
services:
  composer:
    type: php
    build: 
      - composer install
  pma:
    type: phpmyadmin
  node:
    type: node:14
tooling:
  node:
    service: node
  npm:
    service: node